version: "3.8"

services:
  person-db:
    image: postgres:15
    container_name: salesflow-flow-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesflow-db
    ports:
      - "5432:5432"
    volumes:
      - person-db-data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: salesflow-localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init:/etc/localstack/init/ready.d"

  prometheus:
    image: prom/prometheus:latest
    container_name: salesflow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  person-db-data:
