services:
  person-db:
    image: postgres:15
    container_name: salesflow-person-service
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesflow-person
    ports:
      - "5433:5432"
    volumes:
      - person-db-data:/var/lib/postgresql/data

#  plan-service:
#    build: .
#    container_name: person-service
#    restart: always
#    env_file:
#      - ./local.env
#    ports:
#      - "7071:7071"
#    depends_on:
#      - person-db

volumes:
  person-db-data:
