services:
  sales-db:
    image: postgres:15
    container_name: salesflow-sale-service
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesflow-sale
    ports:
      - "5434:5432"
    volumes:
      - sale-db-data:/var/lib/postgresql/data

#  sale-service:
#    build: .
#    container_name: sale-service
#    restart: always
#    env_file:
#      - ./local.env
#    ports:
#      - "7071:7071"
#    depends_on:
#      - sale-db

volumes:
  sale-db-data:
