name: PR Workflow - Microservices

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  person-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/person-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew clean build

  plan-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/plan-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew clean build

  sales-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/sales-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew clean build
